# Generated by Django 4.2.7 on 2023-11-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baxadir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
        migrations.RemoveField(
            model_name='furnituremodel',
            name='category',
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baxadir.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='location',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='baxadir.location'),
            preserve_default=False,
        ),
    ]
