# Generated by Django 4.2.7 on 2023-12-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baxadir', '0003_alter_category_options_alter_furnituremodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '-Помещение', 'verbose_name_plural': '-Помещения'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'ТОВАР', 'verbose_name_plural': 'ТОВАРЫ'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='location',
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baxadir.category', verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='furnituremodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baxadir.location', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Размер'),
        ),
    ]
