# Generated by Django 4.2.7 on 2023-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baxadir', '0004_alter_location_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='furniture_images/', verbose_name='Фотография')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Модель товара',
                'verbose_name_plural': 'Модели товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='size',
            name='furniture_model',
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AddField(
            model_name='location',
            name='Category',
            field=models.ManyToManyField(to='baxadir.category'),
        ),
        migrations.DeleteModel(
            name='FurnitureModel',
        ),
        migrations.AddField(
            model_name='model',
            name='size',
            field=models.ManyToManyField(to='baxadir.size'),
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ManyToManyField(to='baxadir.model'),
        ),
    ]
