# Generated by Django 4.2.7 on 2023-12-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baxadir', '0005_model_alter_size_options_remove_size_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '--- Категория товара', 'verbose_name_plural': '--- Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '---- Помещение', 'verbose_name_plural': '---- Помещения'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': '-- Модель товара', 'verbose_name_plural': '-- Модели товаров'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': '- Размер', 'verbose_name_plural': '- Размеры'},
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, verbose_name='Сумма')),
                ('model', models.ManyToManyField(to='baxadir.model', verbose_name='Модели')),
                ('size', models.ManyToManyField(to='baxadir.size', verbose_name='Модели')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baxadir.category', verbose_name='Категория')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baxadir.location', verbose_name='Помещение')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baxadir.model', verbose_name='Модель')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baxadir.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'Количество',
            },
        ),
    ]
