# Generated by Django 4.2.7 on 2023-12-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baxadir', '0006_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baxadir.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='count',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baxadir.location', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='count',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baxadir.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='count',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baxadir.size', verbose_name='Размер'),
        ),
    ]
